import { cloneModelParameters, defaultModelParameters } from "./modelParameters.js";

export function createInitialAppState() {
  return {
    running: false,
    tick: 0,
    consumers: [],
    producers: [],
    government: null,
    assetMarket: null,
    realEstate: null,
    financialMarket: null,
    creditCycle: null,
    rates: null,
    marketOutcome: null,
    causalDecomposition: null,
    earlyWarning: null,
    externalActors: null,
    classAnalysis: null,
    vulnerabilities: null,
    macroFinancial: null,
    sentiment: null,
    information: null,
    behavior: null,
    external: null,
    policyCredibility: null,
    perceived: null,
    historicalScenario: null,
    sectorState: null,
    flowLedger: null,
    modelParameters: cloneModelParameters(defaultModelParameters),
    modelReliability: null,
    calibrationDataset: null,
    metrics: {},
    history: [],
    flows: [],
    events: [],
    markers: [],
    selected: null,
    hovered: null,
    charts: {},
    config: {},
    policy: null,
    policyQueue: null,
    previousAveragePrice: 10,
    previousAverageWage: 12,
    smoothedInflation: 0,
    smoothedWageGrowth: 0,
    priceDrivers: {
      demandPull: 0,
      costPush: 0,
      shortage: 0,
      expectations: 0
    },
    debug: {
      lastSuccessfulTickTime: 0,
      errors: [],
      suppressVisualUpdates: false,
      lastErrorSignature: "",
      lastErrorAt: 0
    },
    lastFrameTime: 0,
    lastRenderAt: 0,
    accumulator: 0,
    positions: {
      consumers: [],
      producers: [],
      government: { x: 0, y: 0, r: 24 }
    },
    shock: {
      label: "충격 없음",
      ticksRemaining: 0,
      demandMultiplier: 1,
      productivityMultiplier: 1,
      pricePressure: 0
    },
    game: {
      mode: "sandbox",
      modeName: "기본 실험",
      status: "active",
      targetTicks: null,
      startTick: 0,
      scenarioName: "기본 실험",
      score: 0,
      lastScore: 0,
      scoreTrend: 0,
      bestScore: 0,
      failReason: "",
      winReason: "",
      counters: {},
      objectives: [],
      activeEvent: null,
      nextEventTick: 18,
      wasRunningBeforeEvent: false,
      eventsSurvived: 0,
      policyToastAt: 0,
      summary: {}
    },
    ui: {
      detailMode: "summary",
      activeDetailGroup: "overview",
      largeEconomyMode: false,
      lastInspectorUpdateTick: -1,
      lastChartUpdateTick: -1,
      lastCanvasRenderTick: -1,
      lastHeavyInspectorTick: -1,
      compactResults: true,
      chartsAvailable: true,
      canvasPositionCacheKey: "",
      kpiAnimationFrameIds: {},
      lazyResultCache: {},
      openDetailGroups: {}
    }
  };
}
